add posibility to remove recipe, add global alert
knowde-academy/cookbook-react pull request #10
Opened 2021-08-13 10:29 UTC by bartekguz

Add possibility to remove recipe.
Add global alert `react-tostify`

2021-08-13 12:34 UTC, Aliath requested changes

2021-08-13 12:34 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +      console.warn('Cannot delete recipe.');
`toast.error`?

2021-08-13 13:35 UTC, Aliath commented on src/hooks/useAuth/useAuth.ts
> +      toast.error('Login failed!', {
Do not shout at user 😉

2021-08-13 13:36 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +const Transition = React.forwardRef(function Transition(
`const Transition = ...(function Transition(`

Something is wrong right here 😄

2021-08-13 13:36 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +  const [open, setOpen] = useState(false);
What is open?

2021-08-13 13:36 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +      history.push('/');
What about `history.goBack` or `/recipes`?

2021-08-13 13:37 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +        aria-labelledby="alert-dialog-slide-title"
`recipe-delete-dialog-title`

2021-08-13 13:38 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +        aria-describedby="alert-dialog-slide-description"
`recipe-delete-dialog-description`

2021-08-13 16:35 UTC, bartekguz commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +const Transition = React.forwardRef(function Transition(
Do you mean get rid of `React.`?

2021-08-13 20:05 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +const Transition = React.forwardRef(function Transition(
That's another thing but you define function `Transition` twice - the first time by `function Transition` and the second by assignment `forwardRef` result.

2021-08-13 20:31 UTC, bartekguz commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +const Transition = React.forwardRef(function Transition(
Hmm... as before this is the code from the material-ui example: 
https://material-ui.com/components/dialogs/#AlertDialogSlide.tsx

I tried to define this function as you wrote - one time and it doesn't work.
Can you give me an example how to do it?

2021-08-13 21:22 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +const Transition = React.forwardRef(function Transition(
Ok, it's all about the content of `Transition` component. In general it is not a good practice to define different things under the same name. In this case we want to pass reference via `forwardRef` and the problem is eslint that requires name for wrapped function.

to summary: there are three solutions
a) ignore it and just keep the `Transition` as it is right now
b) rename `const Transition` to `const TransitionWithRef`
c) use eslint ignore to calm down the linter

pick whatever you want :D

2021-08-14 08:43 UTC, Aliath approved these changes
🎸 👋

2021-08-14 12:10 UTC, merged