Feature/pagination-query-params
knowde-academy/cookbook-react pull request #12
Opened 2021-08-14 16:01 UTC by bartekguz

Add pagination using url query params.
Fix tests.

2021-08-15 23:54 UTC, Aliath requested changes
Good job! 🥇 

Anyway :D I can see some things that can just be done better - please take a look on it.

2021-08-15 23:54 UTC, Aliath commented on src/services/recipeService.ts
> +    count: response.headers['X-Total-Count'] ?? 0,
I am sure that total count will not be sent as response header. 😄  But for now that's pretty k.

2021-08-15 23:54 UTC, Aliath commented on src/hooks/usePagination/usePagination.ts
> +      pathname: location.pathname,
You can just skip `pathname` field - then only search will be applied.

2021-08-15 23:54 UTC, Aliath commented on src/hooks/usePagination/usePagination.ts
> +    if (urlParams.get('page') === `${DEFAULT_PAGE}`) {
Well, do not remove parameters once it is equal to default values. It may be just weird experience when your address changes and nothing really happens.

2021-08-15 23:54 UTC, Aliath commented on src/hooks/usePagination/usePagination.ts
> +    return getQueryParams(urlParams);
```typescript
const page = urlParams.get('page');
const perPage = urlParams.get('per_page');

return { page, perPage };
```

Is there any extra target of `getQueryParams`? 😄

2021-08-15 23:54 UTC, Aliath commented on src/hooks/usePagination/usePagination.ts
> +const supportedParams = ['page', 'per_page'];
What about keep it in different variables:
`const QUERY_PAGE = 'page'`

etc. and export&use these variables in code below and test file?

2021-08-15 23:54 UTC, Aliath commented on src/hooks/usePagination/usePagination.test.tsx
> +    const { queryParams } = getHookData(history);
This may be a good catch. Let's assume that we will extend this pagination by url filters - we can use it in easy way. 👍 

But then the name `usePagination` is not correct, because all the things inside are not related only to pagination but also search phrases and other filters. What about rename it into `useQueryString`?

Let's try do research about how to write this hook according to [good principles](https://www.typescriptlang.org/docs/handbook/2/generics.html#working-with-generic-type-variables) of typescript.

2021-08-15 23:54 UTC, Aliath commented on src/types/recipes.ts
> +export type DataQueryParams = {
`QueryStringParams` 🤔

2021-08-15 23:54 UTC, Aliath commented on src/services/recipeService.ts
> +    count: response.headers['X-Total-Count'] ?? 0,
A little thing - let's use f.e. `100` as fallback - even if the backend is not ready yet for this feature, it can be easier to test 😃

2021-08-15 23:54 UTC, Aliath commented on src/services/recipeService.ts
> +function generateQueryString(obj: any): string {
[Axios does this on it own](https://github.com/axios/axios#example). 👀

2021-08-16 07:16 UTC, bartekguz commented on src/hooks/usePagination/usePagination.ts
> +    return getQueryParams(urlParams);
The purpose of this function was to check if the query params entered by the user are allowed (this is why the supportedParams variable was introduced earlier). 
But I think you are right and I will simplify it :)

2021-08-16 08:09 UTC, bartekguz commented on src/hooks/usePagination/usePagination.ts
> +const supportedParams = ['page', 'per_page'];
I deleted it because now I think it's unnecessary

2021-08-16 08:09 UTC, Aliath commented on src/hooks/usePagination/usePagination.ts
> +const supportedParams = ['page', 'per_page'];
Ya, it's understandable rn :P

2021-08-16 08:10 UTC, Aliath commented on src/hooks/usePagination/usePagination.ts
> +    return getQueryParams(urlParams);
query params can be modified by third party libraries such as Google Analytics, it's better not to validate them but just get specific values from specific ones

2021-08-16 09:48 UTC, Aliath requested changes

2021-08-16 09:48 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +      search: `?${urlParams}`,
`?` is not required

2021-08-16 09:48 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +    urlParams.set('page', numNewPage.toString());
Let's define constants that will keep query param names inside them:

`const PER_PAGE_PARAM = 'per_page'`

It can be used globally so it's a nice practice to keep it consistent.

2021-08-16 09:48 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +  const changePage = (
I think that this method should get only one parametr - `newPage`. The `_event` arguments etc. should be handled in view component:

```tsx
<TablePagination
    onPageChange={(_event, page) => changePage(page)}
...
```

2021-08-16 09:48 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +  const changePage = (
Thanks to it you do not have to handle event argument.

2021-08-16 09:48 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +    return { page, perPage };
Let's try automatize this, I mean get all the properties from query string and return them in camelCase form.

example querystring: `?page=1&some_property=value`
output:
```
{
  "page": 1,
  "someProperty": "value"
}
```

2021-08-16 09:48 UTC, Aliath commented on src/services/recipeService.ts
> +    params: { params },
{ params }

2021-08-16 09:48 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +  const { changePerPage, changePage, queryParams } = useQueryString();
In order to automatize query string detection - let's try to use generic types:

```tsx
const { ..., queryParams } = useQueryString<{ page: string, perPage: string }>();
```

2021-08-16 09:48 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +  const { changePerPage, changePage, queryParams } = useQueryString();
Then the type of queryParams object will be: 
```ts
{ page: string, perPage: string }
```

2021-08-16 09:48 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +      const { data, count } = await getRecipes(queryParams);
Once object with querystring will be automatized and will return all the properties from url, you have to filter them before you put it in request.

2021-08-16 09:48 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +            page={parseInt(queryParams.page, 10) - 1}
-1? 👀

2021-08-16 11:02 UTC, bartekguz commented on src/components/RecipesList/RecipesList.tsx
> +            page={parseInt(queryParams.page, 10) - 1}
-1 has to be here, because from the documentation we know that: 
prop `page` -> `The zero-based index of the current page.`

so in order to work properly we have to adapt it to this indexing from 0

2021-08-16 11:16 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +            page={parseInt(queryParams.page, 10) - 1}
ok

2021-08-17 06:24 UTC, Aliath requested changes

2021-08-17 06:24 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +    console.log('obj', obj);
Remove console log

2021-08-17 06:24 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +      const { data, count } = await getRecipes(filteredQueryParams);
This is the place where you can format camelCased data to snake_case, filter fields that will be send to backend, etc.
```tsx
... = getRecipes({
  page: fileteredQueryParams.page,
  per_page: filteredQueryParams.perPage,
})

2021-08-17 06:24 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +  const filteredQueryParams = useMemo((): QueryStringParams => {
Let's rename filteredQueryParams to queryParams (because we do not want to filter it as I told you before).

2021-08-17 06:24 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +  const filteredQueryParams = useMemo((): QueryStringParams => {
```suggestion
  const queryParams = useMemo((): T => {
    // here return all the fields from querystring
  }
```

2021-08-17 06:24 UTC, Aliath commented on src/hooks/usePagination/useQueryString.ts
> +export const useQueryString = () => {
```suggestion
export const useQueryString = <T>() => {
```

Let's define a typescript generic type to tell TS what we expect from query string.

2021-08-17 08:54 UTC, Wojtach approved these changes

2021-08-18 07:06 UTC, Aliath approved these changes

2021-08-18 07:09 UTC, merged