CB-62-add-possibilty-to-sort-recipes-list
knowde-academy/cookbook-react pull request #13
Opened 2021-08-18 09:37 UTC by Wojtach

https://team-1626248039387.atlassian.net/jira/software/projects/CB/boards/1?selectedIssue=CB-62&text=react

2021-08-18 10:15 UTC, bartekguz requested changes

2021-08-18 10:15 UTC, bartekguz commented on src/components/DefaultLayout/DefaultLayout.tsx
> +      <SortBar />
UP:
If it is visible for example on recipe details page then it breaks the "Back to recipes" button, so it would be best to limit the visibility of the bar to the list of recipes and the main page IMO

2021-08-18 10:27 UTC, Aliath requested changes

2021-08-18 10:27 UTC, Aliath commented on src/hooks/useFilter/useFilter.ts
> +import { useQueryString } from 'hooks/useQueryString/useQueryString';
hooks should not be listed inside directory

suggested file name change: `src/hooks/useFilter/useFilter.ts` -> `src/hooks/useFilter.ts`

2021-08-18 11:06 UTC, Wojtach commented on src/hooks/useFilter/useFilter.ts
> +import { useQueryString } from 'hooks/useQueryString/useQueryString';
Rest of custom hooks are created in own directories ex. hooks/customHook/customHook.ts. Why this one should be treated in other way?

2021-08-18 12:13 UTC, bartekguz requested changes

2021-08-18 12:13 UTC, bartekguz commented on src/pages/Recipes/Recipes.tsx
> +      <RecipesList />
I think that `<SortBar>` component should be inside `<RecipesList>`

2021-08-19 07:14 UTC, Wojtach commented on src/pages/Recipes/Recipes.tsx
> +      <RecipesList />
I think that <SortBar /> shouldn`t be inside <RecipeList> because its placement in DOM is not inside <RecipeList> but under header on Recipes page.

2021-08-19 07:14 UTC, Aliath commented on src/hooks/useFilter/useFilter.ts
> +import { useQueryString } from 'hooks/useQueryString/useQueryString';
Oh, I missed it - let's keep it. We will fix it during code cleanup

2021-08-19 07:16 UTC, Aliath commented on src/pages/Recipes/Recipes.tsx
> +      <RecipesList />
`<SortBar>` should be part of `<RecipesList>`. Example - we can render `<RecipesList>` on home page (/) and  sortbar won't be visible but it actually should be

2021-08-19 07:19 UTC, Aliath commented on src/pages/Recipes/Recipes.tsx
> +      <RecipesList />
About the position - you can use f.e. `position: fixed` to place it under the header

2021-08-19 07:50 UTC, Wojtach commented on src/pages/Recipes/Recipes.tsx
> +      <RecipesList />
You got me, you are right

2021-08-19 08:04 UTC, Aliath approved these changes
nice job! 💯

2021-08-19 09:08 UTC, bartekguz reviewed
👀 

<img width="1440" alt="Zrzut ekranu 2021-08-19 o 11 06 50" src="https://user-images.githubusercontent.com/58951573/130041770-07e7cf4d-b4d2-4995-b703-f1809608705d.png">

2021-08-19 10:05 UTC, bartekguz approved these changes

2021-08-19 10:15 UTC, merged