Feature/CB-51-Add-CRUD-Products
knowde-academy/cookbook-react pull request #16
Opened 2021-08-19 11:57 UTC by bartekguz

https://team-1626248039387.atlassian.net/jira/software/projects/CB/boards/1?selectedIssue=CB-51

2021-08-19 12:51 UTC, Aliath requested changes

2021-08-19 12:51 UTC, Aliath commented on src/components/ProductsList/Product/Product.scss
> +.container {
This class is over-abused 😄 , what about `product-container`?

2021-08-19 12:51 UTC, Aliath commented on src/pages/Products/Products.tsx
> +    <>
What is the target of fragment?

2021-08-19 12:51 UTC, Aliath commented on src/hooks/useProducts/useProducts.ts
> +export const useProducts = () => {
Nice one

2021-08-19 12:51 UTC, Aliath commented on src/hooks/useProducts/useProducts.ts
> +      if (error.response.status === 422) {
Hmm, that's weird - does backend send any error messages about it?

2021-08-19 12:51 UTC, Aliath commented on src/components/ProductsList/ProductsList.tsx
> +    return <div className="products-error">Request failed!</div>;
Do not shout at user

2021-08-19 12:51 UTC, Aliath commented on src/components/ProductsList/ProductsList.tsx
> +import { Product } from './Product';
What about

`src/components/ProductsList/Product.tsx` -> `src/components/ProductItem/ProductItem.tsx`
`src/components/ProductsList/ProductAddForm.tsx` -> `src/components/ProductAddForm/ProductAddForm.tsx`
`src/components/ProductsList/ProductEditForm.tsx` -> `src/components/ProductAddForm/ProductEditForm.tsx`

2021-08-19 13:06 UTC, Aliath requested changes

2021-08-19 13:06 UTC, Aliath commented on src/components/ProductsList/Product/Product.scss
> +  &__product-list-items {
It feels like BEM went wrong 😄  If you feel that something abuses block/element statements - let's create another block:

```css
.container__product-list {}
.container__product-list-items {}

// vs
.product-list {}
.product-list__item {}
```

2021-08-19 13:06 UTC, Aliath commented on src/components/ProductsList/Product/Product.tsx
> +type Mode = 'read' | 'edit';
```suggestion
type ViewMode = 'read' | 'edit';
```

2021-08-20 07:17 UTC, bartekguz commented on src/pages/Products/Products.tsx
> +    <>
I used an fragment here because I was displaying 2 components when testing. 
I forgot to delete 😵‍💫

2021-08-20 07:23 UTC, bartekguz commented on src/hooks/useProducts/useProducts.ts
> +      if (error.response.status === 422) {
Backend sends error as below:

<img width="533" alt="Zrzut ekranu 2021-08-20 o 09 20 55" src="https://user-images.githubusercontent.com/58951573/130195758-8f38e653-1025-4521-a426-c84c15a10d21.png">

"Unprocessable entity" sounds weird for me, so I decided to check error code and return custom messaage.

What do you think? Can it stay that way or handle it another way?

2021-08-20 07:32 UTC, Aliath commented on src/hooks/useProducts/useProducts.ts
> +      if (error.response.status === 422) {
Unprocessable entity is not enough explicit info to treat it as entry duplicate 🤔  Let's take a look on response content - does backend send any extra info about issue?

2021-08-20 07:45 UTC, bartekguz commented on src/hooks/useProducts/useProducts.ts
> +      if (error.response.status === 422) {
🤔  Should I connect `data` from `config.data` and `name` from `data.errors.name`? 
Isn't that weird? :D 

I'll talk to BE to return the full message because it's an option instead of splitting it

<img width="1077" alt="Zrzut ekranu 2021-08-20 o 09 41 24" src="https://user-images.githubusercontent.com/58951573/130198283-9bc8a3c3-b31b-4e98-8eef-606101f5074c.png">

2021-08-20 07:55 UTC, bartekguz commented on src/components/ProductsList/ProductsList.tsx
> +import { Product } from './Product';
`src/components/ProductsList/ProductEditForm.tsx` -> `src/components/ProductAddForm/ProductEditForm.tsx`
Did you mean `-> src/components/ProductEditForm/ProductEditForm.tsx`?

2021-08-20 08:04 UTC, bartekguz commented on src/hooks/useProducts/useProducts.ts
> +      if (error.response.status === 422) {
So far I've changed to something like this:

```const onAdd = async (name: string) => {
    try {
      const result = await createProduct(name);
      setProducts([...products, result]);

      toast.success('Product added successfully', {
        position: toast.POSITION.BOTTOM_CENTER,
      });
    } catch (error) {
      toast.error(`Product ${name} ${error.response.data.errors.name[0]}`, {
        position: toast.POSITION.BOTTOM_CENTER,
      });
    }
  };```

2021-08-20 08:05 UTC, Aliath commented on src/components/ProductsList/ProductsList.tsx
> +import { Product } from './Product';
exactly 😄

2021-08-20 08:06 UTC, Aliath commented on src/hooks/useProducts/useProducts.ts
> +      if (error.response.status === 422) {
that's ok

2021-08-20 10:45 UTC, Wojtach commented on src/components/ProductsList/ProductsListItem.tsx
> +      </Dialog>
You can use here RemoveModal

2021-08-20 10:46 UTC, Wojtach commented on src/components/ProductsList/ProductsListItem.tsx
> +        keepMounted
You can use here RemoveModal component

2021-08-20 10:49 UTC, Wojtach commented on src/components/ProductsList/ProductsList.tsx
> +            key={product.id}
I think it would be better for user if newest product could be displayed at top of product list.

2021-08-20 10:51 UTC, Wojtach commented on src/components/ProductsList/ProductsListItem.tsx
> +        onClose={handleCloseDialog}
You can use RemoveModal here

2021-08-20 12:11 UTC, Aliath requested changes

2021-08-20 12:11 UTC, Aliath commented on src/components/Modal/Modal.tsx
> +          {`Are you sure you want to delete this ${toDelete}?`}
```suggestion
          Are you sure you want to delete this {toDelete}?
```

2021-08-20 12:11 UTC, Aliath commented on src/hooks/useProducts/useProducts.ts
> +  const [isLoading, setIsLoading] = useState(false);
👀  requestState?

2021-08-20 12:11 UTC, Aliath commented on src/components/ProductsList/ProductsList.tsx
> +            isLoading={isLoading}
```suggestion
            isLoading={requestState === 'loading'}
```

2021-08-20 12:12 UTC, Aliath commented on src/components/Modal/Modal.tsx
> +          {`Are you sure you want to delete this ${toDelete}?`}
Well we can also skip `toDelete` parameter. I would say that user knows where delete button was clicked

2021-08-20 12:12 UTC, Aliath commented
conflicts to resolve 😛

2021-08-20 12:25 UTC, bartekguz commented on src/hooks/useProducts/useProducts.ts
> +  const [isLoading, setIsLoading] = useState(false);
Are you sure about that?
RequestState refers to fetch data from API and depending on this state the product list is rendered or not so I am not sure if I can do that there. 

The isLoading state says if the product editing process is finished. 

If I use RequestState here it probably won't work because after editing I don't render again the list of products, I just do it like this:

```
const index = products.findIndex(
        (productToFind) => productToFind.id === product.id
      );
      const productsToEdit = [...products];
      productsToEdit[index] = { ...result };
```

2021-08-20 12:27 UTC, Aliath commented on src/hooks/useProducts/useProducts.ts
> +  const [isLoading, setIsLoading] = useState(false);
my bad

but name `isCommentPending` will dispel all doubts 😛

2021-08-23 07:27 UTC, Wojtach approved these changes

2021-08-23 07:28 UTC, ggajdek approved these changes

2021-08-23 07:29 UTC, Aliath requested changes

2021-08-23 07:29 UTC, Aliath commented on src/pages/Products/Products.tsx
> +import { ProductsList } from '../../components/ProductsList';
Relative import

2021-08-23 07:29 UTC, Aliath commented on src/components/ProductsList/ProductsListItem.tsx
> +      className={`product-container ${
What about use `clsx`?
```suggestion
      className={clsx('product-container', isEditPending && 'product-container--loading')}
```

2021-08-23 08:56 UTC, Aliath approved these changes

2021-08-23 08:58 UTC, merged