[CB-47] Limit creating recipes only to logged users
knowde-academy/cookbook-react pull request #28
Opened 2021-09-07 12:05 UTC by bartekguz

https://team-1626248039387.atlassian.net/jira/software/projects/CB/boards/1?selectedIssue=CB-47&text=react

2021-09-07 12:26 UTC, Wojtach requested changes

2021-09-07 12:26 UTC, Wojtach commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +      history.push('/');
There should be used history.goBack (), because of query params in URL

2021-09-07 12:32 UTC, bartekguz commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +      history.push('/');
Hmm, you're a little right, but I changed it because when a user goes into the detailed recipe view and selects edit recipe and edits the recipe correctly, then they are redirected back to the detailed recipe view. At this point, if he presses the delete button, it will redirect him to the edit page of the recipe, which does not exist. 

We can choose which situation is better, but in general it can be added in the details of the recipe that if there is no such then it redirects to the home page 🤔

2021-09-08 06:57 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +      history.push('/');
As you use `history.push` in update component you can pass second argument - the state.

We can do following thing: if this state has property `{ getBackToList: true }` we use `router.push('/recipes')` in other case we can use `history.goBack()`. WDYT?

2021-09-08 07:04 UTC, bartekguz commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +      history.push('/');
I looked in the documentation for something similar, because I didn't know such a thing existed, but I didn't find it 🤷🏻 Apparently I checked too shallowly :D This is a great option. Could you please see the last commit where I solved the problem in a different way and check if this solution is ok too? If not, we'll change it to what you suggested :)

2021-09-08 07:06 UTC, Aliath commented on src/pages/RecipeDetails/RecipeDetails.tsx
> +      history.push('/');
That's fine too, good job! 👏

2021-09-08 07:08 UTC, Aliath approved these changes

2021-09-08 07:08 UTC, Aliath commented on src/components/DefaultLayout/DefaultLayout.tsx
>          <>{children}</>
I'm not sure if `<></>` are still required

2021-09-08 07:08 UTC, Aliath commented on src/components/FloatingButton/FloatingButton.tsx
> +  const [open, setOpen] = useState(false);
What's open 😄

2021-09-08 07:08 UTC, Aliath commented on src/components/RecipeForms/RecipeForm.tsx
> +  const isUserAuthorized = !!user;
This variable can be used in many places across all application, what about move it to `useAuth` hook?

2021-09-08 07:51 UTC, Wojtach approved these changes

2021-09-08 07:52 UTC, merged