Added comments
knowde-academy/cookbook-react pull request #6
Opened 2021-08-06 12:00 UTC by Wojtach

https://team-1626248039387.atlassian.net/jira/software/projects/CB/boards/1?selectedIssue=CB-54

2021-08-06 15:11 UTC, Aliath requested changes
Well the feature works well - kudos! 🥇 

However there are things that can be done better. 😄 

**From the UX side:**
Once "comment edit" action is called it would be better to replace card content with textarea, where user can edit the content of comment. We can do this with the following instruction:

- Let's create a state inside `Comment` component that decides about `mode` - it can take two states: `read` | `edit` where the default is `read`
- Once edit button is clicked let's set this `mode` to `edit`
- If `mode` is equal to `read` - render card
- If `mode` is equal to `edit` - render `CommentFormEdit` instead of card component


**From the code side:**
Implementing validation mechanisms by our own is not as easy as it seems. :D The behavior with blur is correct but with many lines of logic we makes the component code unreadable and we have to implement these mechanisms along all the forms. Instead of this we can use vendor that will solve this problems on its own.

2021-08-16 09:31 UTC, Aliath requested changes

2021-08-16 09:31 UTC, Aliath commented on src/components/RecipeComments/CommentForm/CommentForm.tsx
> +    recipe_id: string
camelCase? 😄

2021-08-16 09:31 UTC, Aliath commented on src/services/recipeService.ts
> +  id: number,
Comments are totally different structure in database - we do not have to pass two of ids (recipe & comment) - we can easily identify this by comment id.

2021-08-16 09:31 UTC, Aliath commented on src/hooks/useComments/useComments.ts
> +      commentsToEdit[index] = { ...result };
Nice one!

2021-08-16 09:31 UTC, Aliath commented on src/hooks/useComments/useComments.ts
> +  const onEdit = async (data: CommentData, recipe_id: string, id: number) => {
Let's reverse order of arguments - id, data.

2021-08-16 09:31 UTC, Aliath commented on src/components/RecipeComments/RecipeComments.tsx
> +        <p className="comments-container__error">
What about wrap it in `<Alert>` from material ui?

2021-08-16 09:31 UTC, Aliath commented on src/hooks/useComments/useComments.ts
> +      setComments(comments.filter((comment) => comment.id !== result.id));
👏

2021-08-16 09:31 UTC, Aliath commented on src/components/RecipeComments/CommentFormEdit/CommentFormEdit.tsx
> +  modeToRead,
`restoreReadMode`? 👀

2021-08-16 09:41 UTC, bartekguz commented on src/components/RecipeComments/RecipeComments.tsx
> +        <p className="comments-container__error">
As for the alert, if you did a rebase, you should have added `react-toastify` so maybe just use it instead of `<Alert>` from material ui to be the same?

example:
`import { toast } from 'react-toastify';

toast.error('Something went wrong', {
        position: toast.POSITION.BOTTOM_CENTER,
      });`

2021-08-16 09:49 UTC, Wojtach commented on src/services/recipeService.ts
> +  id: number,
I was following api contract where are required both of them [PUT]/api/v1/recipes/:recipe_id/comments/:id
Should i contact with BE devs, and disscuss about that?

2021-08-16 09:52 UTC, Aliath commented on src/services/recipeService.ts
> +  id: number,
Well, the param name is pretty fine but the thing is to use camelCase in JS functions. Once you read object properties that's ok but if you create functions that manipulate the data then avoid this_method_of_casing 😄

2021-08-16 13:16 UTC, Aliath commented on src/services/recipeService.ts
> +      recipeId: +recipeId,
This field (`recipeId`) should be snake_cased 😄  beacuse it is response from the backend side

2021-08-16 13:18 UTC, Aliath commented on src/components/RecipeComments/CommentForm/CommentForm.tsx
> +  } = useForm();
Let's make it more aggresive - if field is invalid display error on blur

2021-08-16 13:20 UTC, Aliath commented on src/components/RecipeComments/CommentForm/CommentForm.tsx
> +  } = useForm();
What about add `loading` state to comment. When request is pending you can set `opacity: 0.75;` to make "pending" impression

2021-08-17 08:23 UTC, Aliath approved these changes
Such a nice code! Nice job 😎

2021-08-17 08:29 UTC, bartekguz approved these changes

2021-08-17 08:36 UTC, ggajdek approved these changes

2021-08-17 08:42 UTC, merged