Cb 50 add signin signup
knowde-academy/cookbook-react pull request #7
Opened 2021-08-09 12:17 UTC by bartekguz

# Add signin, signup forms.
Add `yup` and `react-hook-form` libraries to validate forms

User can signin with example credentials: 
mail: `admin@gmail.com`
password: `admin`

<img width="1440" alt="Zrzut ekranu 2021-08-9 o 14 15 24" src="https://user-images.githubusercontent.com/58951573/128704720-397b4047-b2af-4213-9917-322a13bcb319.png">

<img width="1440" alt="Zrzut ekranu 2021-08-9 o 14 15 42" src="https://user-images.githubusercontent.com/58951573/128704712-a1c12d1c-85c2-4814-aae0-c4d26fe328e5.png">

2021-08-09 12:32 UTC, Aliath requested changes
Let's get rid of `yup` - it's a large library, and we should simply shift a large part of the responsibility to the backend (including more accurate validations). In this way, we will avoid various types of conflicts when changing requirements, etc.

The other part with authorization is nice, but we can improve UI:

What about something like this? (Maybe Sign Up should have other bg-color :D )
![image](https://user-images.githubusercontent.com/28493823/128706323-6c004098-567c-44b5-a02f-89b25212dc3d.png)

What about validation on blur? It would give us better UX impression - let's take a look over docs how to use it.

Once errors are visible we can see a layout shift - do you have any ideas of how to fix it?

![image](https://user-images.githubusercontent.com/28493823/128707458-f05e64a5-3087-419f-a85c-c6ce7b55357d.png)
Can we shift it not to hide "user" element?

2021-08-09 12:32 UTC, Aliath commented on src/components/SignInForm/SignInForm.scss
> +  -webkit-box-shadow: 0 2px 4px rgba(0, 0, 0, .1), 0 8px 16px rgba(0, 0, 0, .1);
We do not need to attach browser prefixes - built in plugin do this by itself

2021-08-09 12:32 UTC, Aliath commented on src/components/SignInForm/SignInForm.tsx
> +import { yupResolver } from '@hookform/resolvers/yup';
`yup` is really nice library but I think that we do not need all the features from inside. 😄 

I would prefer to implement email validation just like the `react-hook-form` documentation says:

```jsx
<input type="text" placeholder="Email" {...register("Email", {required: true, pattern: /^\S+@\S+$/i})} />
```

But you can split RegExp to another file and use as helper.

2021-08-09 12:32 UTC, Aliath commented on src/types/user.ts
> +export interface SignUpModel {
With types you can do sth like this: 

```ts
export type SignUpModel = Pick<User, 'nickname' | 'email' | 'password'> & { confirmPassword: User['password'] };
```

2021-08-09 12:32 UTC, Aliath commented on src/utils/yupSchema.ts
> +const yupPassword = yup
Hmm, I would prefer to validate it the base way - check length of content. The requirements about the password strength should be controlled by backend side.

Once we get HTTP response error we can parse the content and check what's wrong with specific fields - let's follow backend instructions about password strength.  But despite it - nice code. 😃

2021-08-09 12:44 UTC, Aliath requested changes

2021-08-09 12:44 UTC, Aliath commented on src/components/FlashAlert/FlashAlert.tsx
> +function Alert(props: AlertProps) {
What is the target of this HOC component? 😛

2021-08-09 12:44 UTC, Aliath commented on src/hooks/useAuth/useAuth.ts
> +      // eslint-disable-next-line no-console
Once `no-console` is a crime that you often commit, what about add it to the global eslint config rules?

2021-08-09 12:57 UTC, bartekguz commented on src/components/FlashAlert/FlashAlert.tsx
> +function Alert(props: AlertProps) {
> What is the target of this HOC component? 😛

I just took this from the example:
https://material-ui.com/components/snackbars/#CustomizedSnackbars.tsx

It didn't work without it :c

2021-08-09 13:00 UTC, bartekguz commented
> Once errors are visible we can see a layout shift - do you have any ideas of how to fix it?

You're right. Maybe I can just make space for errors before they appear?

2021-08-09 13:01 UTC, bartekguz commented on src/hooks/useAuth/useAuth.ts
> +      // eslint-disable-next-line no-console
> Once errors are visible we can see a layout shift - do you have any ideas of how to fix it?


You're right. Maybe I can just make space for errors before they appear?

2021-08-09 13:20 UTC, Aliath commented on src/components/FlashAlert/FlashAlert.tsx
> +function Alert(props: AlertProps) {
OK, in this case it is understandable :D

It may be caused by context. If some component passes context and the other one is supposed to get this - they should appear in different component trees.

2021-08-09 13:20 UTC, Aliath commented on src/hooks/useAuth/useAuth.ts
> +      // eslint-disable-next-line no-console
Sounds great! 🚀

2021-08-10 11:10 UTC, Aliath requested changes
We're keep movin towards correct solution! 💪

2021-08-10 11:10 UTC, Aliath commented on src/components/SignInForm/SignInForm.tsx
> +                      label={error ? error.message : 'Password'}
Do not modify label. It's all about accessibility purposes. Instead of this - show `helperText`. To avoid layout shift you can try pass just space: `helperText=" "`.

2021-08-10 11:10 UTC, Aliath commented on src/components/SignInForm/SignInForm.tsx
> +              className="sign-in-form__loginButton"
Let's avoid camelCase in CSS classes - what about `__login-button`?

2021-08-10 11:10 UTC, Aliath commented on src/components/SignUpForm/SignUpForm.tsx
> +                    value: /\S+@\S+\.\S+/,
What about create `src/helpers/validation.ts` file and include this RegExp as `EMAIL_REGEXP` variable? 😛

2021-08-10 11:39 UTC, merged